---
name: Deploy/Destroy bastion to p2-sandbox

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select action to perform"
        type: choice
        required: true
        options:
          - "deploy"
          - "destroy"
        default: "deploy"
  push:
    branches:
      - feat/terragrunt

jobs:
  deploy:
    permissions: write-all
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terragrunt/non-prod/dev/ap-southeast-2/ec2_bastion
    env:
      REGION: ap-southeast-2
      ENV: dev
      STACK_NAME: p2-sandbox
      ROOTSTACK: projecthub
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ENDPOINT: projecthub.p2-sandbox.practera.com
      ACM_NAME: cdn.p2-sandbox.practera.com
      DB_HOST: db.internal.p2-sandbox.practera.com
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Terragrunt and OpenTofu
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: 0.77.22
          tofu_version: 1.6.0
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
      - name: Get AWS Organization Number
        id: AWS_ORG
        run: |
          P2SANDBOX=$(echo $AWS_ACCOUNT_ID | jq -r .P2SANDBOX)
          echo "::add-mask::$P2SANDBOX"
          echo "P2SANDBOX=$P2SANDBOX" >> $GITHUB_OUTPUT
      - name: Configure AWS Credentials from P2SANDBOX Account
        uses: ./.github/actions/aws-oidc
        with:
          role-to-assume: arn:aws:iam::${{ steps.AWS_ORG.outputs.P2SANDBOX }}:role/github-restricted-role-to-assume
          region: ${{ env.REGION }}
      - name: .env create
        run: |
          cat >> files/.env <<EOF
          OPENAI_API_KEY=$OPENAI_API_KEY
          EMAIL_USER=$EMAIL_USER
          EMAIL_PASS=$EMAIL_PASS
          EMAIL_HOST=sandbox.smtp.mailtrap.io
          EMAIL_PORT=2525
          EMAIL_PROVIDER=mailtrap

          GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
          GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
          ADMIN_USERS="rodney@practera.com,wes@practera.com,megan.sitoy@practera.com,shawn@practera.com,chaw@practera.com,terence@practera.com"
          AUTO_REGISTER_DOMAIN="practera.com"

          DATABASE_URL=$DATABASE_URL
          NEXT_PUBLIC_AUTH_URL=https://$ENDPOINT

          EOF
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: .pgpass create
        run: |
          USERNAME=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-CoreDBSecret-$ENV| jq --raw-output '.SecretString' | tr -d '\n' | jq -r '.username')
          PASSWORD=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-CoreDBSecret-$ENV| jq --raw-output '.SecretString' | tr -d '\n' | jq -r '.password')
          HOST=$DB_HOST
          POST=5432

          cat >> files/.pgpass <<EOF
          $HOST:$POST:*:$USERNAME:$PASSWORD
          EOF
      - name: terragrunt plan
        run: |
          terragrunt plan
      
      - name: terragrunt apply or destroy
        run: |
          if [ "${{ github.event.inputs.action }}" == "deploy" ]; then
            terragrunt apply -auto-approve
          else
            terragrunt destroy -auto-approve
          fi
